[package]
name = "image2mes"
version = "0.1.0"
edition = "2021"

[dependencies]
png = "0.17.6"
structopt = "0.3"
anyhow = "1.0.66"
bitvec = "1"
serde = "1.0.158"
serde_json = "1.0.94"
scan_fmt = "0.2.6"
byteorder = "1.4.3"
