[package]
name = "sdformat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
byteorder = "1.4.3"
clap = "4.1.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
