name: firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: binutils-arm-none-eabi gcc-arm-none-eabi libnewlib-arm-none-eabi python3 python3-pip
        version: 1.0
    - name: install pip depencencies
      run: pip3 install pyelftools Jinja2
    - name: update submodules
      run: git submodule update --init
      shell: bash
    - name: compile libopencm3
      run: cd libopencm3 && make TARGETS='stm32/f1'
      shell: bash
    - name: compile gpu
      run: cd gpu/mesgpu && make mesgpu.bin && cd ../..
      shell: bash
    - name: compile cpu
      run: cd cpu/mescpu && mkdir -p bin && touch bin/symbols.inc && make mescpu.elf && python3 extract_symbols.py mescpu.elf > bin/symbols.inc && make mescpu.bin && cd ../..
      shell: bash
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: mes-firmware
        path: cpu/mescpu/mescpu.bin gpu/mesgpu/mesgpu.bin    
