name: firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
    - name: install dependencies
      run: |
        dnf -y groupinstall 'C Development Tools and Libraries' 'Development Tools'
        dnf -y install arm-none-eabi-binutils-cs arm-none-eabi-gcc-cs arm-none-eabi-newlib python3 python3-pip
      shell: bash
    - name: install pip depencencies
      run: pip3 install pyelftools Jinja2
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: compile libopencm3
      run: cd libopencm3 && make TARGETS='stm32/f1' && cd ..
      shell: bash
    - name: compile gpu
      run: cd gpu/mesgpu && make mesgpu.bin && cd ../..
      shell: bash
    - name: compile cpu
      run: cd cpu/mescpu && mkdir -p bin && echo "" > bin/symbols.inc && make mescpu.elf && python3 extract_symbols.py mescpu.elf > bin/symbols.inc && make mescpu.bin && cd ../..
      shell: bash
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: mes-firmware
        path: |
          cpu/mescpu/mescpu.bin
          gpu/mesgpu/mesgpu.bin    
